# Generated by Django 5.0 on 2023-12-05 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0002_comment"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="article",
            name="categories",
        ),
        migrations.RemoveField(
            model_name="comment",
            name="article",
        ),
        migrations.RenameField(
            model_name="article",
            old_name="pub_date",
            new_name="created_at",
        ),
        migrations.RemoveField(
            model_name="article",
            name="status",
        ),
        migrations.AlterField(
            model_name="article",
            name="title",
            field=models.CharField(max_length=200),
        ),
        migrations.DeleteModel(
            name="Category",
        ),
        migrations.DeleteModel(
            name="Comment",
        ),
    ]
