# Generated by Django 5.0 on 2023-12-05 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0003_remove_article_categories_remove_comment_article_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="photo",
            field=models.ImageField(blank=True, null=True, upload_to="article_photos/"),
        ),
        migrations.AddField(
            model_name="article",
            name="sources",
            field=models.TextField(blank=True),
        ),
    ]
